apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bot-uplink
  name: bot-uplink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bot-uplink
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: bot-uplink
    spec:
      containers:
        - env:
            - name: ADMINS
              valueFrom:
                configMapKeyRef:
                  key: ADMINS
                  name: env
            - name: BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: BOT_TOKEN
                  name: env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env
            - name: GIGACHAT_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: GIGACHAT_TOKEN
                  name: env
            - name: HF_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: HF_TOKEN
                  name: env
            - name: NOTIFICATION_BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: NOTIFICATION_BOT_TOKEN
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_DB_IP
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB_IP
                  name: env
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST_AUTH_METHOD
                  name: env
            - name: POSTGRES_INITDB_ARGS
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_INITDB_ARGS
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: QDRANT_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: QDRANT_API_KEY
                  name: env
            - name: QDRANT_URL
              valueFrom:
                configMapKeyRef:
                  key: QDRANT_URL
                  name: env
            - name: ROOT_PASS
              valueFrom:
                configMapKeyRef:
                  key: ROOT_PASS
                  name: env
            - name: TELEGRAM_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: TELEGRAM_TOKEN
                  name: env
            - name: url
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: env
          image: bot-uplink
          name: bot-uplink
          volumeMounts:
            - mountPath: /home/pino/perseus_chat/var/data/
              name: bot-uplink-claim0
      restartPolicy: Always
      volumes:
        - name: bot-uplink-claim0
          persistentVolumeClaim:
            claimName: bot-uplink-claim0
