services:
  postgresDB:
    image: postgres
    ports:
     - 5432:5432
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
    env_file:
     - config/postgres.env
#    secrets:
#     - db-secrets
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - net
  adminer:
    image: adminer
    restart: always
    depends_on:
      postgresDB:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - net
  bot-uplink:
    restart: always
    container_name: bot-uplink
    image: bot-uplink
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
#      chroma:
#        condition: service_healthy
      postgresDB:
        condition: service_healthy 
    volumes:
     - type: bind
       source: /home/pino/hidden/data/
       target: /home/pino/perseus_chat/var/data/
    env_file:
     - .env
    networks:
     - net
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: /home/pino/hidden/proxy/nginx.conf
        target: /home/pino/perseus_chat/etc/nginx/conf.d/default.conf 
        read_only: true
    networks:
      - net

#secrets:
#   db-secrets:
#     file: postgres-secrets.txt

volumes:
  index_data:
    driver: local
  backups:
    driver: local
  pgdata:

networks:
  net:
    driver: bridge